#############################################################################
# Makefile for building: kern
# Generated by qmake (3.0) (Qt 5.4.0)
# Project:  kern.pro
# Template: app
# Command: /home/u296464/sw/QT5.4/5.4/gcc_64/bin/qmake -spec linux-g++ CONFIG+=debug -o Makefile kern.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIE $(DEFINES)
INCPATH       = -I../../sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++ -I. -I. -Isrc -Iui -Iinclude -I../../sw/QT5.4/5.4/gcc_64/include -I../../sw/QT5.4/5.4/gcc_64/include/QtWidgets -I../../sw/QT5.4/5.4/gcc_64/include/QtGui -I../../sw/QT5.4/5.4/gcc_64/include/QtCore -I. -I.
QMAKE         = /home/u296464/sw/QT5.4/5.4/gcc_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kern1.0.0
DISTDIR = /home/u296464/kern/qt2/.tmp/kern1.0.0
LINK          = g++
LFLAGS        = -Wl,-rpath,/home/u296464/sw/QT5.4/5.4/gcc_64 -Wl,-rpath,/home/u296464/sw/QT5.4/5.4/gcc_64/lib
LIBS          = $(SUBLIBS) -L/home/u296464/sw/QT5.4/5.4/gcc_64/lib -lQt5Widgets -lQt5Gui -lQt5Core -lGL -lpthread 
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/main.cpp \
		src/mainwindow.cpp \
		src/analysis.cpp qrc_gui_resource.cpp \
		moc_mainwindow.cpp
OBJECTS       = main.o \
		mainwindow.o \
		analysis.o \
		qrc_gui_resource.o \
		moc_mainwindow.o
DIST          = ../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/linux.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/qconfig.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resources.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/moc.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/uic.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/lex.prf \
		kern.pro include/mainwindow.h \
		include/analysis.h src/main.cpp \
		src/mainwindow.cpp \
		src/analysis.cpp
QMAKE_TARGET  = kern
DESTDIR       = #avoid trailing-slash linebreak
TARGET        = kern


first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

$(TARGET): ui_mainwindow.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kern.pro ../../sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++/qmake.conf ../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_pre.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/shell-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/linux.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-base.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-unix.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/qconfig.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_functions.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_config.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++/qmake.conf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_post.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exclusive_builds.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_pre.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resolve_config.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_post.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/warn_on.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resources.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/moc.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/opengl.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/uic.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/thread.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/testcase_targets.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exceptions.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/yacc.prf \
		../../sw/QT5.4/5.4/gcc_64/mkspecs/features/lex.prf \
		kern.pro \
		src/gui_resource.qrc \
		/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Widgets.prl \
		/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Gui.prl \
		/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Core.prl
	$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile kern.pro
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_pre.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/shell-unix.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/unix.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/linux.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/gcc-base-unix.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-base.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/common/g++-unix.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/qconfig.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_clucene_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_core_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_declarative_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designer_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_enginio_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_gui_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_help_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_location_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_network_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_platformsupport_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qml_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quick_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_script_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_sql_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_svg_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkit_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webkitwidgets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_webview_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_x11extras_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xml_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_functions.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt_config.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++/qmake.conf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/spec_post.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exclusive_builds.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_pre.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resolve_config.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/default_post.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/warn_on.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/qt.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/resources.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/moc.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/opengl.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/uic.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/unix/thread.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/testcase_targets.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/exceptions.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/yacc.prf:
../../sw/QT5.4/5.4/gcc_64/mkspecs/features/lex.prf:
kern.pro:
src/gui_resource.qrc:
/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Widgets.prl:
/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Gui.prl:
/home/u296464/sw/QT5.4/5.4/gcc_64/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-g++ CONFIG+=debug -o Makefile kern.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents src/gui_resource.qrc $(DISTDIR)/
	$(COPY_FILE) --parents include/mainwindow.h include/analysis.h $(DISTDIR)/
	$(COPY_FILE) --parents src/main.cpp src/mainwindow.cpp src/analysis.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui/mainwindow.ui ui/mainwindow.ui $(DISTDIR)/


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

compiler_rcc_make_all: qrc_gui_resource.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_gui_resource.cpp
qrc_gui_resource.cpp: src/gui_resource.qrc \
		src/ToolBar/PHA.png \
		src/ToolBar/DPSD.png \
		src/ToolBar/ToF.png \
		src/Buttons/Power.png \
		src/Buttons/Blue.png \
		src/Buttons/Yellow.png \
		src/Buttons/Halt.png \
		src/Buttons/Pause.png \
		src/Buttons/FastFoward.png \
		src/Buttons/FastReverse.png \
		src/Buttons/Green.png \
		src/Buttons/Play.png \
		src/ToolBar/CloseButton.png \
		src/ToolBar/OpenButton.png \
		src/ToolBar/InfoTagsButton.png \
		src/ToolBar/SaveButton.png \
		src/ToolBar/AddfromCDButton.png \
		src/ToolBar/Symbol-zip.png \
		src/ToolBar/SaveasButton.png \
		src/ToolBar/Stoppuhren/TUhr1.png \
		src/ToolBar/Stoppuhren/Stoppuhr3.png \
		src/ToolBar/Stoppuhren/StoppUhr.png \
		src/Buttons/HZDR.png \
		src/Buttons/HZDR_Icon.png
	/home/u296464/sw/QT5.4/5.4/gcc_64/bin/rcc -name gui_resource src/gui_resource.qrc -o qrc_gui_resource.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp
moc_mainwindow.cpp: ui_mainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QVariant \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvariant.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobal.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qconfig.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlogging.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qflags.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmutex.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstring.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qchar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiterator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qisenum.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpair.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdebug.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qhash.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlocale.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvector.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpoint.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qset.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregexp.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QAction \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qaction.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmargins.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrect.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsize.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpalette.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcolor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qrgb.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qbrush.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qregion.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qline.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtransform.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qimage.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfont.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcursor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfile.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qicon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QApplication \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QComboBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcombobox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QCommandLinkButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QDoubleSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QGridLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qgridlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qboxlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHeaderView \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QLabel \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlabel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenu \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenu.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenuBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QProgressBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qprogressbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QPushButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpacerItem \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QVBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QWidget \
		include/analysis.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QString \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTextStream \
		include/mainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QFileDialog \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qfiledialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdir.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QList \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QUrl \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTime \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatetime.h \
		include/mainwindow.h
	/home/u296464/sw/QT5.4/5.4/gcc_64/bin/moc $(DEFINES) -I/home/u296464/sw/QT5.4/5.4/gcc_64/mkspecs/linux-g++ -I/home/u296464/kern/qt2 -I/home/u296464/kern/qt2 -I/home/u296464/kern/qt2/src -I/home/u296464/kern/qt2/ui -I/home/u296464/kern/qt2/include -I/home/u296464/sw/QT5.4/5.4/gcc_64/include -I/home/u296464/sw/QT5.4/5.4/gcc_64/include/QtWidgets -I/home/u296464/sw/QT5.4/5.4/gcc_64/include/QtGui -I/home/u296464/sw/QT5.4/5.4/gcc_64/include/QtCore include/mainwindow.h -o moc_mainwindow.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_mainwindow.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_mainwindow.h
ui_mainwindow.h: ui/mainwindow.ui
	/home/u296464/sw/QT5.4/5.4/gcc_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

ui_mainwindow.h: ui/mainwindow.ui
	/home/u296464/sw/QT5.4/5.4/gcc_64/bin/uic ui/mainwindow.ui -o ui_mainwindow.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: src/main.cpp ../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QApplication \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobal.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qconfig.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlogging.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qflags.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmutex.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstring.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qchar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiterator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qisenum.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpoint.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsize.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcursor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmargins.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrect.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpalette.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcolor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qrgb.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpair.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregexp.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qbrush.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvector.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qregion.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qline.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtransform.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qimage.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qhash.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfont.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvariant.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdebug.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlocale.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qset.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfile.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QStyle \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qicon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		include/mainwindow.h \
		ui_mainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QVariant \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QAction \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qaction.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QComboBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcombobox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QCommandLinkButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QDoubleSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QGridLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qgridlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qboxlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHeaderView \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QLabel \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlabel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenu \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenu.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenuBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QProgressBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qprogressbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QPushButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpacerItem \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QVBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QWidget \
		include/analysis.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QString \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTextStream \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QFileDialog \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qfiledialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdir.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QList \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QUrl \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTime \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

mainwindow.o: src/mainwindow.cpp include/mainwindow.h \
		ui_mainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QVariant \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvariant.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobal.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qconfig.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlogging.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qflags.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmutex.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstring.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qchar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiterator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qisenum.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpair.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdebug.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qhash.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlocale.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvector.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpoint.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qset.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregexp.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QAction \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qaction.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmargins.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrect.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsize.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpalette.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcolor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qrgb.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qbrush.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qregion.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qline.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtransform.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qimage.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfont.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcursor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfile.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qicon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QApplication \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QComboBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcombobox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QCommandLinkButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QDoubleSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QGridLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qgridlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qboxlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHeaderView \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QLabel \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlabel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenu \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenu.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenuBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QProgressBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qprogressbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QPushButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpacerItem \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QVBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QWidget \
		include/analysis.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QString \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTextStream \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QFileDialog \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qfiledialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdir.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QList \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QUrl \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTime \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o src/mainwindow.cpp

analysis.o: src/analysis.cpp include/analysis.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QWidget \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobal.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qconfig.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfeatures.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsystemdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qprocessordetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcompilerdetection.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypeinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtypetraits.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsysinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlogging.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qflags.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbasicatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_bootstrap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qgenericatomic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_msvc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv7.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv6.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_armv5.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_ia64.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_mips.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_x86.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_cxx11.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_gcc.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qatomic_unix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qglobalstatic.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmutex.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnumeric.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qnamespace.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobjectdefs_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qwindowdefs_win.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstring.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qchar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrefcount.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qarraydata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringbuilder.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qalgorithms.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiterator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qbytearraylist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qscopedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmetatype.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvarlengtharray.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontainerfwd.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qisenum.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qobject_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmargins.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpaintdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qrect.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsize.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpoint.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpalette.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcolor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qrgb.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringlist.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatastream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qiodevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qpair.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregexp.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qstringmatcher.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qbrush.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvector.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qmatrix.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpolygon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qregion.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qline.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtransform.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpainterpath.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qimage.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixelformat.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qpixmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qshareddata.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qhash.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qsharedpointer_impl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfont.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontmetrics.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qfontinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qsizepolicy.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qcursor.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qkeysequence.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qevent.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qvariant.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qmap.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdebug.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qtextstream.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qlocale.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qset.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcontiguouscache.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurl.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qurlquery.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfile.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfiledevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvector2d.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qtouchdevice.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QString \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTextStream \
		include/mainwindow.h \
		ui_mainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QVariant \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QAction \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qaction.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qicon.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qactiongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QApplication \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qcoreapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qeventloop.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdesktopwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qguiapplication.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qinputmethod.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QButtonGroup \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qbuttongroup.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QComboBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcombobox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemdelegate.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyleoption.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtGui/qvalidator.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qregularexpression.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractslider.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qstyle.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qtabwidget.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qrubberband.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qframe.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qabstractitemmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QCommandLinkButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qcommandlinkbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qpushbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractbutton.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QDoubleSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qspinbox.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QGridLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qgridlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlayoutitem.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qboxlayout.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QHeaderView \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qheaderview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractitemview.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qabstractscrollarea.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qitemselectionmodel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QLabel \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qlabel.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMainWindow \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmainwindow.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenu \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenu.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QMenuBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qmenubar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QProgressBar \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qprogressbar.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QPushButton \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpacerItem \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QSpinBox \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QVBoxLayout \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/QFileDialog \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qfiledialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdir.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qfileinfo.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtWidgets/qdialog.h \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QList \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QUrl \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/QTime \
		../../sw/QT5.4/5.4/gcc_64/include/QtCore/qdatetime.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o analysis.o src/analysis.cpp

qrc_gui_resource.o: qrc_gui_resource.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_gui_resource.o qrc_gui_resource.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

